apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: ghcr.io/mostafa6516/devops-checkpoint:latest
        imagePullPolicy: Always
        stdin: true
