apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: ghcr.io/mostafa6516/devops-checkpoint:53121586b34e5bd2f26f8a4ab45da154d7de9bd6
        imagePullPolicy: Always
        stdin: true
