apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: ghcr.io/mostafa6516/devops-checkpoint:ab68269af3462b36d76617daba9aecceabb9da10
        imagePullPolicy: Always
        stdin: true
